### Login:
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "example@mail.com",
  "password": "password123"
}

### Logout:
GET {{host}}/auth/logout
Content-Type: application/json


### GET user-info:
GET {{host}}/auth/user-info
Content-Type: application/json



### find products:
GET {{host}}/products
Content-Type: application/json

### find products by query:
GET {{host}}/products?page=1

### create product:
POST {{host}}/products
Content-Type: application/json

{
  "name": "Ibuprofen",
  "photo": "https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg",
  "supplierId": 24,
  "stock": 25,
  "price": 45.99,
  "category": "Medicine"
}


### delete by id product:
DELETE {{host}}/products/94
Content-Type: application/json


### update product:
PATCH {{host}}/products/64
Content-Type: application/json

{
  "name": "Bepanten"
}

### get suppliers:
GET {{host}}/suppliers
Content-Type: application/json

### add new supplier:
POST {{host}}/suppliers
Content-Type: application/json

{
  "name": "John Smith",
  "address": "Dhaka-12",
  "company": "MedPharm",
  "date": "2024-03-15T00:00:00.000Z",
  "amount": 4500.50,
  "status": "Active"
}

### update supplier:
PATCH {{host}}/suppliers/31
Content-Type: application/json

{
  "name": "John Doe"
}

### get orders with query:
GET {{host}}/orders?order=desc
Content-Type: application/json